"""Cartera button-tap handler and payment graph resume helper — Plan 04-05.

Closes the loop between Plan 04-04 (graph suspends at ``node_awaiting_cartera``
via ``interrupt()``) and actual cartera taps that should resume it.

Public API:
  parse_button_id     — parse ``"aprobar|<case_id>"`` → (action, case_id) tuple
  resume_payment_interrupt — look up case, call ainvoke(Command(resume=...))
  handle_cartera_message   — dispatch text or button tap from cartera phone

Security invariants (threat model 04-05):
  T-04-05-01 — cartera source checked by allowlist in meta.py BEFORE this module
  T-04-05-02 — case_id validated against DB (re-loaded); only open cases proceed
  T-04-05-03 — idempotency: terminal-status case returns no-op (no graph call)
  T-04-05-05 — tap-only: free text and unknown button_ids never mutate state
"""

from __future__ import annotations

from typing import Literal

import structlog

log = structlog.get_logger("features.payment.cartera")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

VALID_ACTIONS: frozenset[str] = frozenset({"aprobar", "rechazar", "info"})

# Statuses that indicate the case is already in a terminal state.
_TERMINAL_STATUSES: frozenset[str] = frozenset({"approved", "rejected", "escalated", "closed"})

# Buttons re-sent when cartera sends free text or an unrecognized tap.
_FALLBACK_BODY = "Toca una opcion para continuar:"

# ---------------------------------------------------------------------------
# parse_button_id
# ---------------------------------------------------------------------------


def parse_button_id(raw: str) -> tuple[str, str] | None:
    """Parse a Meta quick-reply button ``id`` into ``(action, case_id)``.

    Button ids generated by ``node_forward_to_cartera`` follow the format::

        "<action>|<case_id>"

    where ``action`` is one of ``aprobar``, ``rechazar``, ``info``.

    Returns:
        ``(action, case_id)`` tuple when the id is well-formed, otherwise ``None``.

    Security (T-04-05-05): only ``VALID_ACTIONS`` pass through; any other
    action string (including adversarial ids like ``"eliminar|abc"``) returns
    ``None`` and the caller triggers a button re-send instead of a state change.
    """
    if not raw or "|" not in raw:
        return None
    action, case_id = raw.split("|", 1)
    if action not in VALID_ACTIONS or not case_id:
        return None
    return (action, case_id)


# ---------------------------------------------------------------------------
# resume_payment_interrupt
# ---------------------------------------------------------------------------


async def resume_payment_interrupt(
    *,
    action: Literal["aprobar", "rechazar", "info"],
    case_id: str,
    extra: str | None,
    qa_graph: object,
    db_session_factory: object,
    meta_client: object | None = None,
) -> bool:
    """Resume the LangGraph payment flow from its ``interrupt()`` suspension.

    Args:
        action:             One of ``"aprobar"``, ``"rechazar"``, ``"info"``.
        case_id:            UUID of the case to resume.
        extra:              Optional free-text from cartera (used by ``"info"``
                            path so the client receives a follow-up message).
        qa_graph:           Compiled LangGraph graph with a Postgres checkpointer.
        db_session_factory: Async context manager factory (``asynccontextmanager``
                            that yields an ``AsyncSession``).

    Returns:
        ``True``  — case found and either resumed or already terminal (idempotent).
        ``False`` — case not found in DB.

    Security (T-04-05-02):
        Loads the case from DB by ``case_id`` before touching the graph.
        Only ``status="awaiting_cartera"`` proceeds; terminal statuses are
        idempotent no-ops (T-04-05-03).
    """
    import sqlalchemy as sa

    from app.memory.case_store import Case

    async with db_session_factory() as session:
        result = await session.execute(sa.select(Case).where(Case.case_id == case_id))
        case = result.scalars().first()

    if case is None:
        log.warning("cartera.resume.case_not_found", case_id=case_id)
        return False

    if case.status in _TERMINAL_STATUSES:
        log.info(
            "cartera.resume.idempotent_skip",
            case_id=case_id,
            action=action,
            existing_status=case.status,
        )
        return True

    # Resume the graph via LangGraph Command (recommended pattern for interrupt()
    # resumption in LangGraph 1.2.x; Command(resume=value) injects the resume
    # value directly into the interrupt() call site without requiring aupdate_state).
    from langgraph.types import Command

    config = {"configurable": {"thread_id": case.phone}}
    resume_value = {"action": action, "extra": extra}

    final_state = await qa_graph.ainvoke(  # type: ignore[union-attr]
        Command(resume=resume_value), config=config
    )

    log.info("cartera.resume.ok", case_id=case_id, action=action)

    # Dispatch the client-facing message the resumed nodes emitted.
    # node_confirming / node_payment_escalate only PUT an AIMessage into graph
    # state (send_to_client=True) — nothing on the resume path sends it. The
    # webhook's _run_and_dispatch never runs here, so without this the client
    # never receives the confirmation/escalation text.
    if meta_client is not None and isinstance(final_state, dict):
        await _dispatch_client_message(
            final_state=final_state,
            phone=case.phone,
            case_id=case_id,
            meta_client=meta_client,
        )
    return True


async def _dispatch_client_message(
    *,
    final_state: dict,
    phone: str,
    case_id: str,
    meta_client: object,
) -> None:
    """Send the last ``send_to_client`` AIMessage from graph state to the client.

    D-28: the text passes through ``check_outbound`` first. ``payment_approved``
    is taken from the message's own ``additional_kwargs`` — only
    ``node_confirming`` sets it, so a confirmation emitted anywhere else is
    blocked by the firewall exactly like on the webhook dispatch path.
    """
    from langchain_core.messages import AIMessage

    from app.security.output_firewall import check_outbound

    outbound: AIMessage | None = None
    for m in reversed(final_state.get("messages", [])):
        if isinstance(m, AIMessage) and m.additional_kwargs.get("send_to_client"):
            outbound = m
            break
    if outbound is None:
        log.info("cartera.dispatch.no_outbound", case_id=case_id)
        return

    text = str(outbound.content) if outbound.content else ""
    payment_approved = bool(outbound.additional_kwargs.get("payment_approved", False))
    allowed, fw_reason = check_outbound(text, payment_approved=payment_approved)
    if not allowed:
        log.error("cartera.dispatch.firewall_blocked", case_id=case_id, reason=fw_reason)
        return

    try:
        await meta_client.send_text(to=phone, body=text)  # type: ignore[union-attr]
    except Exception as exc:  # noqa: BLE001
        log.error(
            "cartera.dispatch.send_failed",
            case_id=case_id,
            error_type=type(exc).__name__,
        )
        return
    log.info("cartera.dispatch.sent", case_id=case_id, payment_approved=payment_approved)


# ---------------------------------------------------------------------------
# handle_cartera_message
# ---------------------------------------------------------------------------


async def handle_cartera_message(
    *,
    msg: object,
    qa_graph: object,
    meta_client: object,
    db_session_factory: object,
) -> None:
    """Dispatch an inbound message from a cartera phone number.

    Two paths:

    1. **Interactive button tap** — parse the ``button_reply.id``:
       - Valid action + case_id → call ``resume_payment_interrupt``.
       - Unknown / malformed → fall through to button re-send.

    2. **Text / anything else** — re-send the 3 action buttons so the
       cartera knows what to tap.  The most recent ``awaiting_cartera``
       case is found by status (v1 single-cartera assumption, see D-06).
       If no open case is found: silent drop (T-04-05-04).

    Security (T-04-05-05): free text NEVER triggers a state change.
    Security (T-04-05-04): unknown numbers are already dropped BEFORE this
    function is called by the allowlist check in ``meta.py``.
    """
    import sqlalchemy as sa

    from app.memory.case_store import Case

    # ------------------------------------------------------------------
    # Path 1: Interactive button tap
    # ------------------------------------------------------------------
    if msg.type == "interactive" and msg.interactive is not None:  # type: ignore[union-attr]
        raw_id: str | None = msg.interactive.selected_id()  # type: ignore[union-attr]
        parsed = parse_button_id(raw_id or "")
        if parsed is not None:
            action, case_id = parsed
            await resume_payment_interrupt(
                action=action,  # type: ignore[arg-type]
                case_id=case_id,
                extra=None,
                qa_graph=qa_graph,
                db_session_factory=db_session_factory,
                meta_client=meta_client,
            )
            return
        # Fall through — unknown button_id triggers button re-send below.

    # ------------------------------------------------------------------
    # Path 2: Text or unrecognized button — re-send the 3 action buttons
    # ------------------------------------------------------------------

    # v1 single-cartera assumption (D-06): find the latest awaiting_cartera case.
    # ponytail: fragile if cartera handles many concurrent cases; Phase 5+ needs
    # a case-routing ADR.
    async with db_session_factory() as session:
        result = await session.execute(
            sa.select(Case)
            .where(Case.status == "awaiting_cartera")
            .order_by(Case.created_at.desc())
            .limit(1)
        )
        case = result.scalars().first()

    if case is None:
        log.info("cartera.message.no_open_case", from_hash=str(msg.from_)[:6])  # type: ignore[union-attr]
        return

    buttons: list[tuple[str, str]] = [
        (f"aprobar|{case.case_id}", "Aprobar"),
        (f"rechazar|{case.case_id}", "Rechazar"),
        (f"info|{case.case_id}", "Mas info"),
    ]
    await meta_client.send_buttons(  # type: ignore[union-attr]
        to=msg.from_,  # type: ignore[union-attr]
        body=_FALLBACK_BODY,
        buttons=buttons,
    )
    log.info("cartera.message.buttons_resent", case_id=case.case_id)


__all__ = [
    "VALID_ACTIONS",
    "handle_cartera_message",
    "parse_button_id",
    "resume_payment_interrupt",
]
